### PR TITLE
Generate enums for parameters as well as properties

### PR DESCRIPTION
**Pull request by jasonmccampbell**
Hi Lewin, this extends the enum generation to handle properties as well as parameters.

There were a lot of duplicate enums generated and it _seems_ from the docs that a given type is defined once and they don't change it. For example, ResponseValueRenderOption is used multiple times, but remains consistent. So this PR removes the scoping prefix and then de-duplicates the enums. This reduces the code size, but I don't _know_ that it's safe.

I also added 'non_camel_case_types' to the 'allow' header to get rid of a bunch of warnings.

Jason

### CODE REVIEW

**Comment by dermesser** [comment]
I fixed this issue with my own changes now (and fixed some longer-term smells on top). I hope you are not discouraged - as usual, I'd be delighted if you could take a look and see if the new enums are useful. From my cursory glance, the names grow longer, but they should be the right enums :)

e.g.

```rust
/// Parameters for the `values.append` method.                                                                                                                                       │
#[derive(Serialize, Deserialize, Debug, Clone, Default)]                                                                                                                             │
pub struct SpreadsheetsValuesAppendParams {                                                                                                                                          │
    /// General attributes applying to any API call                                                                                                                                  │
    #[serde(flatten)]                                                                                                                                                                │
    pub sheets_params: Option<SheetsParams>,                                                                                                                                         │
    /// Determines how dates, times, and durations in the response should be rendered. This is ignored if response_value_render_option is FORMATTED_VALUE. The default dateTime rende│
r option is [DateTimeRenderOption.SERIAL_NUMBER].                                                                                                                                    │
    #[serde(rename = "responseDateTimeRenderOption")]                                                                                                                                │
    pub response_date_time_render_option: Option<ValuesAppendResponseDateTimeRenderOption>,                                                                                          │
    /// How the input data should be interpreted.                                                                                                                                    │
    #[serde(rename = "valueInputOption")]                                                                                                                                            │
    pub value_input_option: Option<ValuesAppendValueInputOption>,                                                                                                                    │
    /// How the input data should be inserted.                                                                                                                                       │
    #[serde(rename = "insertDataOption")]                                                                                                                                            │
    pub insert_data_option: Option<ValuesAppendInsertDataOption>,                                                                                                                    │
    /// The A1 notation of a range to search for a logical table of data. Values are appended after the last row of the table.                                                       │
    #[serde(rename = "range")]                                                                                                                                                       │
    pub range: String,                                                                                                                                                               │
    /// The ID of the spreadsheet to update.                                                                                                                                         │
    #[serde(rename = "spreadsheetId")]                                                                                                                                               │
    pub spreadsheet_id: String,                                                                                                                                                      │
    /// Determines if the update response should include the values of the cells that were appended. By default, responses do not include the updated values.                        │
    #[serde(rename = "includeValuesInResponse")]                                                                                                                                     │
    pub include_values_in_response: Option<bool>,                                                                                                                                    │
    /// Determines how values in the response should be rendered. The default render option is ValueRenderOption.FORMATTED_VALUE.                                                    │
    #[serde(rename = "responseValueRenderOption")]                                                                                                                                   │
    pub response_value_render_option: Option<ValuesAppendResponseValueRenderOption>,                                                                                                 │
} 

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]                                                                                                                                │[lbo@z420 generate]$ 
pub enum ValuesAppendResponseDateTimeRenderOption {                                                                                                                                  │(failed reverse-i-search)`rsync': diff -u gen/sheetsold.rs gen/sheets_v4_types.^C | less
    Undefined,                                                                                                                                                                       │[lbo@z420 generate]$ 
    /// Instructs date, time, datetime, and duration fields to be output as doubles in "serial number" format, as popularized by Lotus 1-2-3. The whole number portion of the value (│
left of the decimal) counts the days since December 30th 1899. The fractional portion (right of the decimal) counts the time as a fraction of the day. For example, January 1st 1900 │
at noon would be 2.5, 2 because it's 2 days after December 30st 1899, and .5 because noon is half a day. February 1st 1900 at 3pm would be 33.625. This correctly treats the year 190│
0 as not a leap year.                                                                                                                                                                │
    #[serde(rename = "SERIAL_NUMBER")]                                                                                                                                               │
    SERIAL_NUMBER,                                                                                                                                                                   │
    /// Instructs date, time, datetime, and duration fields to be output as strings in their given number format (which is dependent on the spreadsheet locale).                     │
    #[serde(rename = "FORMATTED_STRING")]                                                                                                                                            │
    FORMATTED_STRING,                                                                                                                                                                │
}                                                                                                                                                                                    │
                                                                                                                                                                                     │
impl std::default::Default for ValuesAppendResponseDateTimeRenderOption {                                                                                                            │
    fn default() -> ValuesAppendResponseDateTimeRenderOption {                                                                                                                       │
        ValuesAppendResponseDateTimeRenderOption::Undefined                                                                                                                          │
    }                                                                                                                                                                                │
}                                                                                                                                                                                    │
                                                                                                                                                                                     │
impl std::fmt::Display for ValuesAppendResponseDateTimeRenderOption {                                                                                                                │
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {                                                                                                             │
        let s = match self {                                                                                                                                                         │
            ValuesAppendResponseDateTimeRenderOption::Undefined => write!(f, "undefined"),                                                                                           │
            ValuesAppendResponseDateTimeRenderOption::SERIAL_NUMBER => write!(f, "SERIAL_NUMBER"),                                                                                   │
            ValuesAppendResponseDateTimeRenderOption::FORMATTED_STRING => {                                                                                                          │
                write!(f, "FORMATTED_STRING")                                                                                                                                        │
            }                                                                                                                                                                        │
        };                                                                                                                                                                           │
        Ok(())                                                                                                                                                                       │
    }                                                                                                                                                                                │
}

// ...                                                                                                     
```

**Comment by jasonmccampbell** [comment]
The changes work great -- thank you! And no worries at all, my changes were a first cut while starting to look at the code.

Is it necessary to keep the full scoping in the enum types? It is more ergonomic if the types can be shared (less code, values work across structs), but that only holds true if the types are guaranteed to be the same. Either way, just having the enums is a big help.

Can you add 'non_camel_case_types' to the allow header in templates.py? Without it there are hundreds of compiler warnings which obscure other potentially real issues.

**Comment by dermesser** [comment]
> Is it necessary to keep the full scoping in the enum types? It is more ergonomic if the types can be shared (less code, values work across structs), but that only holds true if the types are guaranteed to be the same. Either way, just having the enums is a big help.

I noticed this too, and wasn't too happy about it. But as you say, just going by name we cannot be sure that the enums are the same, and having one enum with a possibly weird prefix, or one enum with the right name but just the wrong values seems even less ergonomic. With this said, my way of approaching the generated code is through the generated documentation, and because you likely never will look for enums on their own, you will always find the right one by going the Service -> Method -> (Parameter type, Request type) route. Those items will then make it clear how to fill them.

...and because we are already :cowboy_hat_face:-ing around here: Given that APIs are versioned, it may sometimes be even worth modifying the JSON code locally before generating API code and use the `--doc` option to generate code. For example, the Drive and Storage APIs would benefit from this patch:

```diff
--- drive_orig.json     2021-02-01 18:43:41.227551198 +0100
+++ drive.json  2021-02-01 18:42:50.898781782 +0100
@@ -27,10 +27,12 @@
       "description": "Data format for the response.",
       "default": "json",
       "enum": [
-        "json"
+        "json",
+        "media"
       ],
       "enumDescriptions": [
-        "Responses with Content-Type of application/json"
+        "Responses with Content-Type of application/json",
+        "Triggers data download."
       ],
       "location": "query"
     },
```

...so you could add your own enum types or schemas to the JSON schema and generate code from that (benefitting from potential new features in the generator).

> Can you add 'non_camel_case_types' to the allow header in templates.py? Without it there are hundreds of compiler warnings which obscure other potentially real issues.

This is a good idea!

**Comment by jasonmccampbell** [comment]
Thanks for all the help, Lewin, the changes work great. Closing this PR since everything is covered.

**Pull request closed without merging**
