### PR TITLE
Update to Tokio v1, plus additional dependencies - WIP

### PR DESCRIPTION
**Pull request by jasonmccampbell**
Hi Lewin, thanks a lot for putting this crate together, it looks like exactly what I was looking for. If you are interested, here is a PR updating to Tokio v1.0.1, Hyper 0.14, and yup_oauth v5. The changes are minor, mostly adapting to the Streams and StreamExt traits moving out of Tokio.

Moving yup_oauth to v5 didn't have an impact here, but I'm not sure yet if it impacts any of the examples or other uses of this crate.

This PR is very much a work-in-progress, just sending it now for your input. I want to work with the Google Sheets API, but haven't integrated it into my code yet because I wanted to update the dependencies. Hopefully I'll get something testable later this week.

Regards,
Jason

### CODE REVIEW

**Comment by dermesser** [comment]
Have you generated and run code with the new dependencies?

I personally wouldn't expect anything to break, as the code is only using very basic features of hyper, and only a few tokio features.

**Comment by dermesser** [comment]
I checked out your branch in the meantime and tried getting to run the Drive example (my personal benchmark, because it's a full but understandable API :)

It works with a few differences, 1. with updated crates and 2. according API changes.

Your PR would be perfect if you put these changes into it too (and make it work), otherwise I can do that after merging :)

```diff
diff -r 1302eeaccf20 example_crates/drive_example/Cargo.toml
--- a/example_crates/drive_example/Cargo.toml   Sun Jan 10 23:05:59 2021 -0600
+++ b/example_crates/drive_example/Cargo.toml   Mon Jan 11 12:06:21 2021 +0100
@@ -12,6 +12,6 @@
 anyhow = "~1.0"
 serde = "~1.0"
 env_logger = "~0.8"
-hyper-rustls = "~0.20"
-hyper = "~0.13"
-tokio = { version = "~0.2", features = ["rt-core", "io-util", "macros", "fs"] }
+hyper-rustls = { version = "~0.22", features = ["rustls-native-certs"] }
+hyper = { version = "~0.14", features = ["stream"] }
+tokio = { version = "~1.0", features = ["macros", "io-util", "rt", "rt-multi-thread", "fs"] }
diff -r 1302eeaccf20 example_crates/drive_example/src/main.rs
--- a/example_crates/drive_example/src/main.rs  Sun Jan 10 23:05:59 2021 -0600
+++ b/example_crates/drive_example/src/main.rs  Mon Jan 11 12:06:21 2021 +0100
@@ -18,7 +18,7 @@
 
 /// Create a new HTTPS client.
 fn https_client() -> common::TlsClient {
-    let conn = hyper_rustls::HttpsConnector::new();
+    let conn = hyper_rustls::HttpsConnector::with_native_roots();
     let cl = hyper::Client::builder().build(conn);
     cl
 }
```

also PS: thank you for using the crate, but please don't be surprised if something doesn't work right away - I tested the generator script (which itself has grown to be a little beast on its own) on a few select APIs, and I think Sheets API was included, but it's always possible that new fields show up that it doesn't handle yet. For rapidity reasons, I implemented based on the actual APIs, not the formal specification of the discovery docs. :-)

**Comment by jasonmccampbell** [comment]
I updated the three examples with your diffs and got the Google Drive one working. That was good practice as I haven't used the Google APIs before so it was good to see it work (at least list the files) before experimenting with the Sheets API. I've generated the code, but that's as far as I've gotten. Just an evening project, so may be this weekend before I get to it.

Happy to tidy up the PR if you see anything else that should be included.

**Comment by dermesser** [comment]
Looks good! Let me know how it goes from here on, I'm happy to help if you have trouble.

**Pull request merged**
