### PR TITLE
Update generate script to fix issues with calendar:v3

### PR DESCRIPTION
**Pull request by ddboline**
This MR does 2 things:

Update the generate and template scripts to fix issues with calendar:v3:
    - Avoid conflict with rust keywords `self` and `move` in identifiers
    - Properly format DateTime in query parameters

Create minimal example for Google Calendar.

### CODE REVIEW

**Comment by sabify** [comment]
These has been done in PR #12, that the generator can generate apis without issues.
@dermesser I can create another PR and separate the `generator.py` and `template.py` from there before having discussion on the restructure...

**Comment by dermesser** [comment]
> These has been done in PR #12, that the generator can generate apis without issues.
> @dermesser I can create another PR and separate the `generator.py` and `template.py` from there before having discussion on the restructure...

This would greatly help, I agree, and your solution to keyword conflicts is also more general. How about you split off the generate.py improvements, I merge it, and then for this PR we rebase everything but the `move` conflict if-clause?

**Comment by dermesser** [comment]
> This MR does 2 things:
> 
> Update the generate and template scripts to fix issues with calendar:v3:
> - Avoid conflict with rust keywords `self` and `move` in identifiers
> - Properly format DateTime in query parameters
> 
> Create minimal example for Google Calendar.

@ddboline thank you for the PR, it looks quite good! Let me know if you're ok with proceeding as I proposed in the comment above.

**Comment by dermesser** [comment]
PR #16 was just merged, can you try reapplying the changes to current master?

**Comment by ddboline** [comment]
I merged in the changes from master. 
[#16](https://github.com/dermesser/async-google-apis/pull/16) fixed the issues I had with `self` and `master`. 

The only change to generate.py and template.py that remains is the fix for DateTime objects in query parameters.

**Comment by dermesser** [comment]
Awesome, thank you :star_struck:

**Pull request merged**
